/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import pp.ua.lifebook.storage.db.scheme.tables.RepeatType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepeatTypeRecord extends UpdatableRecordImpl<RepeatTypeRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.repeat_type.code</code>.
     */
    public RepeatTypeRecord setCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.repeat_type.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.repeat_type.name</code>.
     */
    public RepeatTypeRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.repeat_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RepeatType.REPEAT_TYPE.CODE;
    }

    @Override
    public Field<String> field2() {
        return RepeatType.REPEAT_TYPE.NAME;
    }

    @Override
    public String component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public RepeatTypeRecord value1(String value) {
        setCode(value);
        return this;
    }

    @Override
    public RepeatTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RepeatTypeRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RepeatTypeRecord
     */
    public RepeatTypeRecord() {
        super(RepeatType.REPEAT_TYPE);
    }

    /**
     * Create a detached, initialised RepeatTypeRecord
     */
    public RepeatTypeRecord(String code, String name) {
        super(RepeatType.REPEAT_TYPE);

        setCode(code);
        setName(name);
    }

    /**
     * Create a detached, initialised RepeatTypeRecord
     */
    public RepeatTypeRecord(pp.ua.lifebook.storage.db.scheme.tables.pojos.RepeatType value) {
        super(RepeatType.REPEAT_TYPE);

        if (value != null) {
            setCode(value.getCode());
            setName(value.getName());
        }
    }
}
