/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import pp.ua.lifebook.storage.db.scheme.tables.TagMomentRelation;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagMomentRelationRecord extends TableRecordImpl<TagMomentRelationRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tag_moment_relation.tag_id</code>.
     */
    public TagMomentRelationRecord setTagId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tag_moment_relation.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tag_moment_relation.moment_id</code>.
     */
    public TagMomentRelationRecord setMomentId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tag_moment_relation.moment_id</code>.
     */
    public Integer getMomentId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TagMomentRelation.TAG_MOMENT_RELATION.TAG_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TagMomentRelation.TAG_MOMENT_RELATION.MOMENT_ID;
    }

    @Override
    public Integer component1() {
        return getTagId();
    }

    @Override
    public Integer component2() {
        return getMomentId();
    }

    @Override
    public Integer value1() {
        return getTagId();
    }

    @Override
    public Integer value2() {
        return getMomentId();
    }

    @Override
    public TagMomentRelationRecord value1(Integer value) {
        setTagId(value);
        return this;
    }

    @Override
    public TagMomentRelationRecord value2(Integer value) {
        setMomentId(value);
        return this;
    }

    @Override
    public TagMomentRelationRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagMomentRelationRecord
     */
    public TagMomentRelationRecord() {
        super(TagMomentRelation.TAG_MOMENT_RELATION);
    }

    /**
     * Create a detached, initialised TagMomentRelationRecord
     */
    public TagMomentRelationRecord(Integer tagId, Integer momentId) {
        super(TagMomentRelation.TAG_MOMENT_RELATION);

        setTagId(tagId);
        setMomentId(momentId);
    }

    /**
     * Create a detached, initialised TagMomentRelationRecord
     */
    public TagMomentRelationRecord(pp.ua.lifebook.storage.db.scheme.tables.pojos.TagMomentRelation value) {
        super(TagMomentRelation.TAG_MOMENT_RELATION);

        if (value != null) {
            setTagId(value.getTagId());
            setMomentId(value.getMomentId());
        }
    }
}
