/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import pp.ua.lifebook.storage.db.scheme.tables.TagPlanRelation;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagPlanRelationRecord extends TableRecordImpl<TagPlanRelationRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tag_plan_relation.tag_id</code>.
     */
    public TagPlanRelationRecord setTagId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tag_plan_relation.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tag_plan_relation.plan_id</code>.
     */
    public TagPlanRelationRecord setPlanId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tag_plan_relation.plan_id</code>.
     */
    public Integer getPlanId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TagPlanRelation.TAG_PLAN_RELATION.TAG_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TagPlanRelation.TAG_PLAN_RELATION.PLAN_ID;
    }

    @Override
    public Integer component1() {
        return getTagId();
    }

    @Override
    public Integer component2() {
        return getPlanId();
    }

    @Override
    public Integer value1() {
        return getTagId();
    }

    @Override
    public Integer value2() {
        return getPlanId();
    }

    @Override
    public TagPlanRelationRecord value1(Integer value) {
        setTagId(value);
        return this;
    }

    @Override
    public TagPlanRelationRecord value2(Integer value) {
        setPlanId(value);
        return this;
    }

    @Override
    public TagPlanRelationRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagPlanRelationRecord
     */
    public TagPlanRelationRecord() {
        super(TagPlanRelation.TAG_PLAN_RELATION);
    }

    /**
     * Create a detached, initialised TagPlanRelationRecord
     */
    public TagPlanRelationRecord(Integer tagId, Integer planId) {
        super(TagPlanRelation.TAG_PLAN_RELATION);

        setTagId(tagId);
        setPlanId(planId);
    }

    /**
     * Create a detached, initialised TagPlanRelationRecord
     */
    public TagPlanRelationRecord(pp.ua.lifebook.storage.db.scheme.tables.pojos.TagPlanRelation value) {
        super(TagPlanRelation.TAG_PLAN_RELATION);

        if (value != null) {
            setTagId(value.getTagId());
            setPlanId(value.getPlanId());
        }
    }
}
