/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import pp.ua.lifebook.storage.db.scheme.tables.Category;
import pp.ua.lifebook.storage.db.scheme.tables.ListItems;
import pp.ua.lifebook.storage.db.scheme.tables.Lists;
import pp.ua.lifebook.storage.db.scheme.tables.Moments;
import pp.ua.lifebook.storage.db.scheme.tables.PlanStatus;
import pp.ua.lifebook.storage.db.scheme.tables.Plans;
import pp.ua.lifebook.storage.db.scheme.tables.Reminders;
import pp.ua.lifebook.storage.db.scheme.tables.RepeatType;
import pp.ua.lifebook.storage.db.scheme.tables.UserSettings;
import pp.ua.lifebook.storage.db.scheme.tables.Users;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.list_items</code>.
     */
    public final ListItems LIST_ITEMS = ListItems.LIST_ITEMS;

    /**
     * The table <code>public.lists</code>.
     */
    public final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>public.moments</code>.
     */
    public final Moments MOMENTS = Moments.MOMENTS;

    /**
     * The table <code>public.plan_status</code>.
     */
    public final PlanStatus PLAN_STATUS = PlanStatus.PLAN_STATUS;

    /**
     * The table <code>public.plans</code>.
     */
    public final Plans PLANS = Plans.PLANS;

    /**
     * The table <code>public.reminders</code>.
     */
    public final Reminders REMINDERS = Reminders.REMINDERS;

    /**
     * The table <code>public.repeat_type</code>.
     */
    public final RepeatType REPEAT_TYPE = RepeatType.REPEAT_TYPE;

    /**
     * The table <code>public.user_settings</code>.
     */
    public final UserSettings USER_SETTINGS = UserSettings.USER_SETTINGS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Category.CATEGORY,
            ListItems.LIST_ITEMS,
            Lists.LISTS,
            Moments.MOMENTS,
            PlanStatus.PLAN_STATUS,
            Plans.PLANS,
            Reminders.REMINDERS,
            RepeatType.REPEAT_TYPE,
            UserSettings.USER_SETTINGS,
            Users.USERS
        );
    }
}
