/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListItems implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer listId;
    private final String  name;
    private final String  comment;
    private final Boolean completed;

    public ListItems(ListItems value) {
        this.id = value.id;
        this.listId = value.listId;
        this.name = value.name;
        this.comment = value.comment;
        this.completed = value.completed;
    }

    public ListItems(
        Integer id,
        Integer listId,
        String  name,
        String  comment,
        Boolean completed
    ) {
        this.id = id;
        this.listId = listId;
        this.name = name;
        this.comment = comment;
        this.completed = completed;
    }

    /**
     * Getter for <code>public.list_items.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.list_items.list_id</code>.
     */
    public Integer getListId() {
        return this.listId;
    }

    /**
     * Getter for <code>public.list_items.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.list_items.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Getter for <code>public.list_items.completed</code>.
     */
    public Boolean getCompleted() {
        return this.completed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ListItems (");

        sb.append(id);
        sb.append(", ").append(listId);
        sb.append(", ").append(name);
        sb.append(", ").append(comment);
        sb.append(", ").append(completed);

        sb.append(")");
        return sb.toString();
    }
}
