/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lists implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer userId;
    private final String  name;
    private final Boolean deleted;

    public Lists(Lists value) {
        this.id = value.id;
        this.userId = value.userId;
        this.name = value.name;
        this.deleted = value.deleted;
    }

    public Lists(
        Integer id,
        Integer userId,
        String  name,
        Boolean deleted
    ) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>public.lists.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.lists.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.lists.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.lists.deleted</code>.
     */
    public Boolean getDeleted() {
        return this.deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Lists (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
