/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plans implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer       id;
    private final String        title;
    private final String        repeated;
    private final String        comments;
    private final String        status;
    private final Integer       userId;
    private final Integer       category;
    private final LocalDateTime dueTime;

    public Plans(Plans value) {
        this.id = value.id;
        this.title = value.title;
        this.repeated = value.repeated;
        this.comments = value.comments;
        this.status = value.status;
        this.userId = value.userId;
        this.category = value.category;
        this.dueTime = value.dueTime;
    }

    public Plans(
        Integer       id,
        String        title,
        String        repeated,
        String        comments,
        String        status,
        Integer       userId,
        Integer       category,
        LocalDateTime dueTime
    ) {
        this.id = id;
        this.title = title;
        this.repeated = repeated;
        this.comments = comments;
        this.status = status;
        this.userId = userId;
        this.category = category;
        this.dueTime = dueTime;
    }

    /**
     * Getter for <code>public.plans.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.plans.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>public.plans.repeated</code>. code of RepeatType
     */
    public String getRepeated() {
        return this.repeated;
    }

    /**
     * Getter for <code>public.plans.comments</code>.
     */
    public String getComments() {
        return this.comments;
    }

    /**
     * Getter for <code>public.plans.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.plans.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.plans.category</code>.
     */
    public Integer getCategory() {
        return this.category;
    }

    /**
     * Getter for <code>public.plans.due_time</code>.
     */
    public LocalDateTime getDueTime() {
        return this.dueTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Plans (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(repeated);
        sb.append(", ").append(comments);
        sb.append(", ").append(status);
        sb.append(", ").append(userId);
        sb.append(", ").append(category);
        sb.append(", ").append(dueTime);

        sb.append(")");
        return sb.toString();
    }
}
