/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reminders implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer       id;
    private final Integer       planId;
    private final LocalDateTime remindAt;

    public Reminders(Reminders value) {
        this.id = value.id;
        this.planId = value.planId;
        this.remindAt = value.remindAt;
    }

    public Reminders(
        Integer       id,
        Integer       planId,
        LocalDateTime remindAt
    ) {
        this.id = id;
        this.planId = planId;
        this.remindAt = remindAt;
    }

    /**
     * Getter for <code>public.reminders.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.reminders.plan_id</code>.
     */
    public Integer getPlanId() {
        return this.planId;
    }

    /**
     * Getter for <code>public.reminders.remind_at</code>.
     */
    public LocalDateTime getRemindAt() {
        return this.remindAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reminders (");

        sb.append(id);
        sb.append(", ").append(planId);
        sb.append(", ").append(remindAt);

        sb.append(")");
        return sb.toString();
    }
}
