/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepeatType implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String code;
    private final String name;

    public RepeatType(RepeatType value) {
        this.code = value.code;
        this.name = value.name;
    }

    public RepeatType(
        String code,
        String name
    ) {
        this.code = code;
        this.name = name;
    }

    /**
     * Getter for <code>public.repeat_type.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Getter for <code>public.repeat_type.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RepeatType other = (RepeatType) obj;
        if (code == null) {
            if (other.code != null)
                return false;
        }
        else if (!code.equals(other.code))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RepeatType (");

        sb.append(code);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
