/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String  login;
    private final String  firstName;
    private final String  lastName;
    private final String  email;
    private final String  password;
    private final Boolean isAdmin;
    private final String  language;

    public Users(Users value) {
        this.id = value.id;
        this.login = value.login;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.email = value.email;
        this.password = value.password;
        this.isAdmin = value.isAdmin;
        this.language = value.language;
    }

    public Users(
        Integer id,
        String  login,
        String  firstName,
        String  lastName,
        String  email,
        String  password,
        Boolean isAdmin,
        String  language
    ) {
        this.id = id;
        this.login = login;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.isAdmin = isAdmin;
        this.language = language;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.users.login</code>.
     */
    public String getLogin() {
        return this.login;
    }

    /**
     * Getter for <code>public.users.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Getter for <code>public.users.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Getter for <code>public.users.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    /**
     * Getter for <code>public.users.language</code>. two symbol language code
     */
    public String getLanguage() {
        return this.language;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(login);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(isAdmin);
        sb.append(", ").append(language);

        sb.append(")");
        return sb.toString();
    }
}
