/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pp.ua.lifebook.storage.db.scheme.Keys;
import pp.ua.lifebook.storage.db.scheme.Public;
import pp.ua.lifebook.storage.db.scheme.tables.records.RepeatTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepeatType extends TableImpl<RepeatTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.repeat_type</code>
     */
    public static final RepeatType REPEAT_TYPE = new RepeatType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RepeatTypeRecord> getRecordType() {
        return RepeatTypeRecord.class;
    }

    /**
     * The column <code>public.repeat_type.code</code>.
     */
    public final TableField<RepeatTypeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.repeat_type.name</code>.
     */
    public final TableField<RepeatTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    private RepeatType(Name alias, Table<RepeatTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RepeatType(Name alias, Table<RepeatTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.repeat_type</code> table reference
     */
    public RepeatType(String alias) {
        this(DSL.name(alias), REPEAT_TYPE);
    }

    /**
     * Create an aliased <code>public.repeat_type</code> table reference
     */
    public RepeatType(Name alias) {
        this(alias, REPEAT_TYPE);
    }

    /**
     * Create a <code>public.repeat_type</code> table reference
     */
    public RepeatType() {
        this(DSL.name("repeat_type"), null);
    }

    public <O extends Record> RepeatType(Table<O> child, ForeignKey<O, RepeatTypeRecord> key) {
        super(child, key, REPEAT_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RepeatTypeRecord> getPrimaryKey() {
        return Keys.REPEAT_TYPE_PK;
    }

    @Override
    public RepeatType as(String alias) {
        return new RepeatType(DSL.name(alias), this);
    }

    @Override
    public RepeatType as(Name alias) {
        return new RepeatType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RepeatType rename(String name) {
        return new RepeatType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RepeatType rename(Name name) {
        return new RepeatType(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
