/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Moments implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer   id;
    private final LocalDate date;
    private final String    description;
    private final Integer   userId;

    public Moments(Moments value) {
        this.id = value.id;
        this.date = value.date;
        this.description = value.description;
        this.userId = value.userId;
    }

    public Moments(
        Integer   id,
        LocalDate date,
        String    description,
        Integer   userId
    ) {
        this.id = id;
        this.date = date;
        this.description = description;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.moments.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.moments.date</code>.
     */
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Getter for <code>public.moments.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.moments.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Moments other = (Moments) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (date == null) {
            if (other.date != null)
                return false;
        }
        else if (!date.equals(other.date))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Moments (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(description);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
