/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagPlanRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer tagId;
    private final Integer planId;

    public TagPlanRelation(TagPlanRelation value) {
        this.tagId = value.tagId;
        this.planId = value.planId;
    }

    public TagPlanRelation(
        Integer tagId,
        Integer planId
    ) {
        this.tagId = tagId;
        this.planId = planId;
    }

    /**
     * Getter for <code>public.tag_plan_relation.tag_id</code>.
     */
    public Integer getTagId() {
        return this.tagId;
    }

    /**
     * Getter for <code>public.tag_plan_relation.plan_id</code>.
     */
    public Integer getPlanId() {
        return this.planId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TagPlanRelation other = (TagPlanRelation) obj;
        if (tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!tagId.equals(other.tagId))
            return false;
        if (planId == null) {
            if (other.planId != null)
                return false;
        }
        else if (!planId.equals(other.planId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        result = prime * result + ((this.planId == null) ? 0 : this.planId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TagPlanRelation (");

        sb.append(tagId);
        sb.append(", ").append(planId);

        sb.append(")");
        return sb.toString();
    }
}
