/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import pp.ua.lifebook.storage.db.scheme.tables.Lists;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListsRecord extends UpdatableRecordImpl<ListsRecord> implements Record4<Integer, Integer, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lists.id</code>.
     */
    public ListsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.lists.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lists.user_id</code>.
     */
    public ListsRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.lists.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.lists.name</code>.
     */
    public ListsRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.lists.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lists.deleted</code>.
     */
    public ListsRecord setDeleted(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.lists.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Lists.LISTS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Lists.LISTS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Lists.LISTS.NAME;
    }

    @Override
    public Field<Boolean> field4() {
        return Lists.LISTS.DELETED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Boolean component4() {
        return getDeleted();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Boolean value4() {
        return getDeleted();
    }

    @Override
    public ListsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ListsRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ListsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ListsRecord value4(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public ListsRecord values(Integer value1, Integer value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListsRecord
     */
    public ListsRecord() {
        super(Lists.LISTS);
    }

    /**
     * Create a detached, initialised ListsRecord
     */
    public ListsRecord(Integer id, Integer userId, String name, Boolean deleted) {
        super(Lists.LISTS);

        setId(id);
        setUserId(userId);
        setName(name);
        setDeleted(deleted);
    }

    /**
     * Create a detached, initialised ListsRecord
     */
    public ListsRecord(pp.ua.lifebook.storage.db.scheme.tables.pojos.Lists value) {
        super(Lists.LISTS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setName(value.getName());
            setDeleted(value.getDeleted());
        }
    }
}
