/*
 * This file is generated by jOOQ.
 */
package pp.ua.lifebook.storage.db.scheme.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import pp.ua.lifebook.storage.db.scheme.tables.PlanStatus;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanStatusRecord extends UpdatableRecordImpl<PlanStatusRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.plan_status.code</code>.
     */
    public PlanStatusRecord setCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.plan_status.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.plan_status.name</code>.
     */
    public PlanStatusRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.plan_status.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PlanStatus.PLAN_STATUS.CODE;
    }

    @Override
    public Field<String> field2() {
        return PlanStatus.PLAN_STATUS.NAME;
    }

    @Override
    public String component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public PlanStatusRecord value1(String value) {
        setCode(value);
        return this;
    }

    @Override
    public PlanStatusRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlanStatusRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlanStatusRecord
     */
    public PlanStatusRecord() {
        super(PlanStatus.PLAN_STATUS);
    }

    /**
     * Create a detached, initialised PlanStatusRecord
     */
    public PlanStatusRecord(String code, String name) {
        super(PlanStatus.PLAN_STATUS);

        setCode(code);
        setName(name);
    }

    /**
     * Create a detached, initialised PlanStatusRecord
     */
    public PlanStatusRecord(pp.ua.lifebook.storage.db.scheme.tables.pojos.PlanStatus value) {
        super(PlanStatus.PLAN_STATUS);

        if (value != null) {
            setCode(value.getCode());
            setName(value.getName());
        }
    }
}
